version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker_files/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - node-api
    links:
      - node-api

  node-api:
    depends_on:
      - neo4j
    links:
      - neo4j

