version: "3"
services:
  node-api:
    restart: always
    depends_on:
      - hub
      - neo4j
      - redis
      - rabbitmq
    links:
      - hub
      - neo4j
      - redis
      - rabbitmq

  redis:
    image: redis
    expose:
      - 6379

  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"
