version: "3"
services:
  node-api:
    build:
      context: .
      dockerfile: docker_files/node-api/Dockerfile
    env_file: .env
    command: bash /usr/script/start.sh
    ports:
      - "4000:4000"
    volumes:
      - ./mowy-api/src:/usr/app/src
    depends_on:
      - neo4j
    links:
      - neo4j

  neo4j:
    image: neo4j:4.0
    env_file: .env
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - ./docker_files/neo4j/data:/data
      - ./docker_files/neo4j/plugins:/plugins
      - ./mowy-api/src/seeds/data:/var/lib/neo4j/import/seeds
