version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker_files/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - node-api
    links:
      - node-api

  node-api:
    restart: always
    depends_on:
      - neo4j
      - rabbitmq
    links:
      - neo4j
      - rabbitmq

