version: "3"
services:
  node-api:
    restart: always
    depends_on:
      - hub
      - neo4j
      - redis
      - rabbitmq
    links:
      - hub
      - neo4j
      - redis
      - rabbitmq

  redis:
    image: redis
    expose:
      - 6379

  rabbitmq:
    image: "rabbitmq:3-management"
    tty: true
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/data

  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    env_file: .env
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"

volumes:
    rabbitmq_data: